### ISSUE TITLE
error.StringNotFound

### ISSUE THREAD

**Issue by Mchdms** [fifty-six/zig.SteamManifestPatcher#10] opened 2022-03-08 23:29 UTC
Patcher not working as of 3/8/22. Program returns error.StringNotFound Unable to dump stack trace: FileNotFound.

Happens regardless of admin privileges.

**Comment by themichaelmitchell** [comment] 2022-03-09 01:07
Perhaps a [recent steam update](https://store.steampowered.com/oldnews/125571) removed the following string from the DLL?
https://github.com/fifty-six/zig.SteamManifestPatcher/blob/6669098d4b03a26cfe2d1ec1e9aa2843895870d0/src/main.zig#L13

Current strings I'm seeing in `steamclient.dll`, version `7.13.47.17`, build time `Fri Mar 4 18:45:16 2022`:
```bash
$ strings '.../steamclient.dll' | grep 'Depot download failed'
Depot download failed : error downloading chunk for file "%s" (%s)
Depot download failed : error unpacking chunk for file "%s"
Depot download failed : error downloading manifest %llu (%s)
Depot download failed : error writing chunk for "%s"
Depot download failed : error getting workshop item info (%s)
Depot download failed : workshop item %llu not found
Depot download failed : missing app info for %u
Depot download failed : no workshop depot configured
Depot download failed : Invalid default manifest
Depot download failed : missing license for depots %u
Depot download failed : missing encryption key for depotID %u (%s)
Depot download failed : error starting download for depot manifest %llu
Depot download failed : error decrypting depot manifest %llu
Depot download failed : error decrypting delta manifest %llu
```

**Comment by BioNexus1** [comment] 2022-03-09 20:00
Got process handle.
Module handle address: 5f280000
error.StringNotFound
Unable to dump stack trace: FileNotFound
Press ENTER to close.

same error here

**Comment by emeraldtip** [comment] 2022-03-09 20:47
Same

**Comment by fifty-six** [comment] 2022-03-09 23:36
Yeah I can reproduce this, I'll look into it when I get the chance. Might take a bit.

**Comment by fifty-six** [comment] 2022-03-10 07:01
![downpatching](https://user-images.githubusercontent.com/10470872/157605968-386d5c07-e289-4b81-ae3b-2933e6e24655.png)


Ok so they did remove the string, but it *seems* to be because downpatching is a thing again anyways, so not really sure what to do with this issue. wontfix I guess.

**Closed as completed** 2022-03-11 01:19 UTC
Labels: bug, wontfix
